language: node_js
node_js:
  - '11'
install: npm install
after_script:
  - cd ./public
  - git init
  - git config user.name "LiuGuinv"
  - git config user.email "997207868@qq.com"
  - git add -A
  - git commit -m "Update documents"
  - git push --force "https://${GH_TOKEN}@${GH_REF}" "master:gh-pages"
branches:
  only:
    - master
